# Generated by Django 3.0 on 2020-01-29 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('pro_category_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('contact', models.IntegerField()),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=30)),
                ('pro_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pro_dscript', models.TextField(max_length=50)),
                ('pro_category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itvedantapp1.Category')),
            ],
        ),
    ]
