# Generated by Django 3.0 on 2020-01-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itvedantapp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='contact',
            field=models.BigIntegerField(),
        ),
    ]
