# Generated by Django 3.0.2 on 2020-06-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itvedantapp1', '0004_carts'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pro_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
